version: '3.8'

services:
  image-generator:
    build: .
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
