apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-generator-deployment
  labels:
    app: image-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-generator
  template:
    metadata:
      labels:
        app: image-generator
    spec:
      containers:
      - name: image-generator
        image: gcr.io/YOUR_PROJECT_ID/image-generator:latest
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: image-generator-service
spec:
  selector:
    app: image-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
